### ISSUE TITLE
A bit more in the readme ?

### ISSUE THREAD

**Issue by jbpoline** [ohbm/cobidas-mri#3]
I will give it a shot, but I guess this is to turn the cobidas recommendation into a repro-schema representation, and associate a vue.js front end to fill in the information, correct ?

**Comment by satra** [comment]
yes, that is what is happening in the repo. but i leave it to @Remi-Gau in terms of where help is needed.

**Comment by Remi-Gau** [comment]
>I will give it a shot, but I guess this is to turn the cobidas recommendation into a repro-schema representation, and associate a vue.js front end to fill in the information, correct ?

Exactly.

I was planning to reuse a lot of the stuff we have [there](https://github.com/Remi-Gau/COBIDAS_chckls) to update the readme.

**Comment by jbpoline** [comment]
I just put a sentence and the link to your readme in a PR ...
thanks - it would be fantastic to have that, I plan to push it for Aperture
and other journals !

**Comment by Remi-Gau** [comment]
OK I finally have 5 minutes free from the open-science organization madness (OSOM).

Will start by updating some READMEs starting with this one. 

Thanks @jbpoline for the nudge. ;-p
