### ISSUE TITLE
update ui-changes

### ISSUE THREAD

**Issue by Remi-Gau** [ohbm/cobidas-mri#5]
@satra 

Am trying to catch up.

We should change the changes that have to be made to the ui-code during the github action, no?

Some info is now being read from the `config.js`

See below.

https://github.com/sensein/covid19/blob/master/ui-changes/src/config.js

**Comment by satra** [comment]
@Remi-Gau - the demo-protocol https://github.com/ReproNim/demo-protocol is the simplest to follow. there is a github action there and we use a checksum to fix it to a version of reproschema-ui.

the other is changes/src/config.js, which should be updated to reflect the necessary changes for this repo.

**Comment by satra** [comment]
@Remi-Gau -

this is the correct URL: https://raw.githubusercontent.com/ohbm/cobidas/master/protocols/neurovault/neurovault_schema

current pointer: https://raw.githubusercontent.com/ohbm/cobidas/master/protocols/neurovault_schema

**Comment by Remi-Gau** [comment]
OK so the thing is "running".

I got some issues on the dropdown but that is mostly due on how things are "encoded" in the spreadsheet and things are getting messed up during the conversion.

Will try to solve that.

Closing that for now.

Thanks a lot for your patience @satra
